export const ACCOUNT_STATUS = {
  PENDING: 'PENDING',
  ACTIVE: 'ACTIVE',
  BAN: 'BAN',
}
export const CLASSROOM_ROLE = {
  STUDENT: 'STUDENT',
  TEACHER: 'TEACHER',
  ADMIN: 'ADMIN',
  USER: 'USER',
}
export const CLASSROOM_STATUS = {
  PENDING: 'PENDING',
  ACTIVE: 'ACTIVE',
}
export const NOTIFICATION_STATUS = {
  UNREAD: 'UNREAD',
  READ: 'READ',
}
